# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('open', 'open')], max_length=2),
        ),
    ]
