# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20170602_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
        migrations.AddField(
            model_name='listtodos',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('open', 'open')], default='open', max_length=2),
        ),
    ]
