# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20170607_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listtodos',
            name='todo',
        ),
        migrations.RemoveField(
            model_name='listtodos',
            name='todo_list',
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('complete', 'complete')], default='open', max_length=20),
        ),
        migrations.DeleteModel(
            name='ListToDos',
        ),
    ]
