# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20170613_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='todo_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo_app.ToDoList'),
            preserve_default=False,
        ),
    ]
